// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migraties moeten via een directe Postgres-verbinding (geen pooler): advisory locks werken niet betrouwbaar via Neon pooler.
  // Zet DIRECT_URL in Vercel/Neon (Connection string zonder "-pooler"); DATABASE_URL blijft de pooler-URL voor de runtime.
  datasource: {
    url:
      process.env["DIRECT_URL"]?.trim() ||
      process.env["DATABASE_URL"]?.trim(),
  },
});
